### ISSUE TITLE
GUI crash when encoding and minimizing window.

### ISSUE THREAD

**Issue by 7gxycn08** [mikigal/Anime4K-GUI#31]
```
panic: Assertion failed!
        File: D:/a/cimgui-go/cimgui-go/cwrappers/imgui/imgui_widgets.cpp, Line 783

        Expression: size_arg.x != 0.0f && size_arg.y != 0.0f


goroutine 1 [running, locked to thread]:
github.com/AllenDang/cimgui-go/imgui.init.func1({0xc000013710?, 0xc000086000?}, {0xc000015a00?, 0xc000588cf0?}, 0x7ff6e023c570?)
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/cimgui-go@v1.1.0/imgui/assert.go:28 +0x54
github.com/AllenDang/cimgui-go/imgui.goImguiAssertHandler(0x0?, 0x7ff6e0b47580, 0x2?)
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/cimgui-go@v1.1.0/imgui/assert.go:45 +0x67
github.com/AllenDang/cimgui-go/imgui._Cfunc_wrap_igInvisibleButton(0x2833f90, {0x40800000, 0x0})
        _cgo_gotypes.go:63843 +0x52
github.com/AllenDang/cimgui-go/imgui.InvisibleButton({0xc0002097a0?, 0x0?}, {0x86000?, 0xc0?})
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/cimgui-go@v1.1.0/imgui/cimgui_funcs.go:12673 +0x87
github.com/AllenDang/giu.(*SplitterWidget).Build(0xc000210b40)
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/giu@v0.10.0/ExtraWidgets.go:86 +0x179
github.com/AllenDang/giu.(*RowWidget).Build.func1({0x7ff6e09d0440?, 0xc000210b40?})
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/giu@v0.10.0/Widgets.go:47 +0x11b
github.com/AllenDang/giu.Layout.Range({0xc000210bd0?, 0xc000589100?, 0x7ff6e03c1aa7?}, 0xc0002074d0)
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/giu@v0.10.0/Layout.go:48 +0x87
github.com/AllenDang/giu.(*RowWidget).Build(0xc00020bcc8)
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/giu@v0.10.0/Widgets.go:29 +0x79
github.com/AllenDang/giu.Layout.Build(...)
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/giu@v0.10.0/Layout.go:28
github.com/AllenDang/giu.(*SplitLayoutWidget).Build(0xc0005187e0)
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/giu@v0.10.0/SplitLayout.go:112 +0x8c8
github.com/AllenDang/giu.Layout.Build(...)
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/giu@v0.10.0/Layout.go:28
github.com/AllenDang/giu.Layout.Build(...)
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/giu@v0.10.0/Layout.go:28
github.com/AllenDang/giu.Layout.Build(...)
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/giu@v0.10.0/Layout.go:28
github.com/AllenDang/giu.(*ChildWidget).Build(0xc000203a40)
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/giu@v0.10.0/Widgets.go:122 +0x91
github.com/AllenDang/giu.(*SplitLayoutWidget).Build.(*SplitLayoutWidget).buildChild.func2()
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/giu@v0.10.0/SplitLayout.go:151 +0x175
github.com/AllenDang/giu.(*CustomWidget).Build(0xc00020cbf8?)
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/giu@v0.10.0/ExtraWidgets.go:140 +0x17
github.com/AllenDang/giu.Layout.Build(...)
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/giu@v0.10.0/Layout.go:28
github.com/AllenDang/giu.Layout.Build(...)
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/giu@v0.10.0/Layout.go:28
github.com/AllenDang/giu.(*ColumnWidget).Build(0xc00020b758)
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/giu@v0.10.0/Widgets.go:350 +0x65
github.com/AllenDang/giu.Layout.Build(...)
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/giu@v0.10.0/Layout.go:28
github.com/AllenDang/giu.(*SplitLayoutWidget).Build(0xc000518840)
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/giu@v0.10.0/SplitLayout.go:112 +0x8c8
github.com/AllenDang/giu.Layout.Build(...)
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/giu@v0.10.0/Layout.go:28
github.com/AllenDang/giu.(*WindowWidget).Layout(0xc0002035c0, {0xc000589738, 0x1, 0x1})
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/giu@v0.10.0/Window.go:149 +0x2e5
main.loop(0xc0002aa000)
        C:/Users/Xen3/Anime4K-GUI/gui.go:45 +0x20b2
main.main.func1()
        C:/Users/Xen3/Anime4K-GUI/main.go:112 +0x17
github.com/AllenDang/giu.(*MasterWindow).render(0xc0002aa000)
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/giu@v0.10.0/MasterWindow.go:248 +0x2bb
github.com/AllenDang/cimgui-go/backend.loopCallback()
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/cimgui-go@v1.1.0/backend/backend.go:36 +0x34
github.com/AllenDang/cimgui-go/backend/glfwbackend._Cfunc_igGLFWRunLoop(0x27e9cb0, 0x7ff6e0434a20, 0x7ff6e0434a60, 0x7ff6e0434aa0, 0x7ff6e0434b20)
        _cgo_gotypes.go:364 +0x4d
github.com/AllenDang/cimgui-go/backend/glfwbackend.(*GLFWBackend).Run.func1(0xc000110f01?)
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/cimgui-go@v1.1.0/backend/glfwbackend/glfw_backend.go:264 +0x9f
github.com/AllenDang/cimgui-go/backend/glfwbackend.(*GLFWBackend).Run(0x10?, 0x7ff6e0919f60?)
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/cimgui-go@v1.1.0/backend/glfwbackend/glfw_backend.go:264 +0x32
main.main.(*MasterWindow).Run.func2()
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/giu@v0.10.0/MasterWindow.go:265 +0xcb
github.com/AllenDang/giu.mainthreadCallPlatform(...)
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/giu@v0.10.0/mainthread_windows.go:22
github.com/AllenDang/giu.(*MasterWindow).Run(...)
        C:/Users/Xen3/go/pkg/mod/github.com/!allen!dang/giu@v0.10.0/MasterWindow.go:257
main.main()
        C:/Users/Xen3/Anime4K-GUI/main.go:112 +0x11f
```

**Comment by mikigal** [comment]
I can not reproduce problem, but it was related to Giu (GUI framework). It has been updated in [v1.1.8 ](https://github.com/mikigal/Anime4K-GUI/releases/tag/v1.1.8) - it should fix this issue
